# Generated by Django 3.0.8 on 2020-07-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntuation',
            old_name='follow_date',
            new_name='date',
        ),
    ]
