# Generated by Django 3.0.8 on 2020-07-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_product_currency_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method_id',
        ),
        migrations.DeleteModel(
            name='Payment_data',
        ),
        migrations.DeleteModel(
            name='Payment_method',
        ),
    ]
